version: '3.7'
services:
  MySQL:
    image: mysql:5.7
    container_name: laravelMySQL
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - HaallooNet
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_CONNECTION: 'mysql'
      MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'NeoNest'
      MYSQL_USER: 'fpp-bkk'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]  
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 3s
  BE:
    image: haalloobim/neo-nest-fp:latest
    container_name: laravelBackendApp
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - HaallooNet
    depends_on:
      MySQL:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: MySQL
      DB_PORT: 3306
      DB_DATABASE: pbkk
      DB_USERNAME: 'fpp-bkk'
      DB_PASSWORD: 'pass'
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "MySQL" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 3s
    volumes:
      - connected-volume:/var/www/html
  BE-Migration:
    image: haalloobim/neo-nest-fp:latest
    container_name: laravelBackendMigration
    restart: on-failure
    networks:
      - HaallooNet
    depends_on:
      MySQL:
        condition: service_healthy
    command: php artisan migrate
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - connected-volume:/var/www/html
    depends_on:
      - BE
    networks:
      - HaallooNet
volumes:
  connected-volume:
networks:
  HaallooNet:
    driver: bridge